services:
    BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection:
        public: true
        abstract: true
        arguments:
            # This argument where set with the add arguments pass and comes from webpack_encore.entrypoint_lookup.cache_warmer.
            $builds: ''
            $cache: "@webpack_encore.cache"
            $twigExtension: "@webpack_encore.twig_entry_files_extension"

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeCSSCombineSectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeJavascriptCombineSectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeJQuerySectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeMooToolsSectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeHeadSectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true

    BlackForest\Contao\Encore\EventListener\Frontend\IncludeBodySectionListener:
        parent: BlackForest\Contao\Encore\EventListener\Frontend\AbstractIncludeSection
        public: true
